apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: llm-secrets
  namespace: jobmatch-dev # <--- Дивись, неймспейс збігається з Deployment
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-manager # <--- Використовуємо існуючий Store
    kind: ClusterSecretStore
  target:
    name: llm-secrets # <--- Секрет з такою назвою чекає Deployment
    creationPolicy: Owner
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: openai-api-key
    - secretKey: gemini-api-key
      remoteRef:
        key: gemini-api-key