apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llm-secrets
  namespace: jobmatch-dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secret-manager 
    kind: ClusterSecretStore 
  target:
    name: llm-secrets      
    creationPolicy: Owner
  data:
    - secretKey: openai-api-key
      remoteRef:
        key: openai-api-key
    - secretKey: gemini-api-key
      remoteRef:
        key: gemini-api-key
    - secretKey: claude-api-key
      remoteRef:
        key: claude-api-key