apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: llm-external-secret
  namespace: jobmatch-dev
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: gcp-store
    kind: SecretStore
  target:
    name: llm-secrets
    creationPolicy: Owner
  data:
  - secretKey: openai-api-key
    remoteRef:
      key: openai-api-key
  - secretKey: gemini-api-key
    remoteRef:
      key: openai-api-key
  - secretKey: claude-api-key
    remoteRef:
      key: openai-api-key
